# Generated by Django 6.0.3 on 2026-03-24 19:14

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[users.models.validate_phone_number]),
        ),
    ]
